# -*- coding: utf-8 -*-
"""task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFceacRx8cItmcGfy1WMFEaNw0HIVTeg
"""

import pandas as pd
import matplotlib.pyplot as plt

# ==========================
# Load Excel Dataset
# ==========================
file_path = "ApexPlanet_DataAnalytics_Dataset.xlsx"
df = pd.read_excel(file_path)

# ==========================
# Display Dataset
# ==========================
print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

# ==========================
# Remove Duplicates
# ==========================
df.drop_duplicates(inplace=True)

# Fill missing values
for col in df.select_dtypes(include='number').columns:
    df[col].fillna(df[col].mean(), inplace=True)

for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

# ==========================
# Summary Statistics
# ==========================
print("\nSummary Statistics:")
print(df.describe())

# ==========================
# Correlation Matrix
# ==========================
numeric_df = df.select_dtypes(include='number')
print("\nCorrelation Matrix:")
print(numeric_df.corr())

# ==========================
# Histograms
# ==========================
numeric_df.hist(figsize=(12,8))
plt.tight_layout()
plt.show()

# ==========================
# Bar Chart (Top 10 Categories)
# ==========================
if "Category" in df.columns:
    df["Category"].value_counts().head(10).plot(
        kind="bar",
        figsize=(8,5),
        title="Top Categories"
    )
    plt.xlabel("Category")
    plt.ylabel("Count")
    plt.show()

# ==========================
# Sales Analysis
# ==========================
if "Sales" in df.columns:
    print("\nTotal Sales:", df["Sales"].sum())
    print("Average Sales:", df["Sales"].mean())
    print("Maximum Sales:", df["Sales"].max())
    print("Minimum Sales:", df["Sales"].min())

# ==========================
# Save Cleaned Dataset
# ==========================
df.to_excel("Cleaned_ApexPlanet_Dataset.xlsx", index=False)

print("\nAnalysis Completed Successfully!")
print("Cleaned dataset saved as 'Cleaned_ApexPlanet_Dataset.xlsx'")